### ISSUE TITLE
为什么使用的是老版本的quickjs库

### ISSUE THREAD

**Issue by iStig** [quickjs-ios/quickjs-ios#1]
我pod update后看到一个quickjs-2019-08-10文件夹 看了下代码感觉是比较老的版本 并不是2021-03-27的版本。
比如缺少globalthis的定义。
另外目前是不是只有quickjs- iOS 0.0.7版本，问下如何才能用上0.0.8。

**Comment by samchang8826** [comment]
fixed, sync with latest quickjs https://github.com/bellard/quickjs
